run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gofmt
    - goimports
    - ineffassign
    - unused
  disable:
    - gochecknoglobals

issues:
  exclude-use-default: false
  exclude:
    # allow unchecked Close/Write error where appropriate
    - "Error return value.*(Close|Write).*(is not checked)"
