repos:
- repo: https://github.com/pre-commit/mirrors-gofmt
  rev: v1
  hooks:
  - id: gofmt
    args: ["-s", "-l", "-w"]

- repo: https://github.com/pre-commit/mirrors-goimports
  rev: v0.1.5
  hooks:
  - id: goimports
    args: ["-local", "github.com/antitree/go-pillage-registries"]

- repo: https://github.com/pre-commit/mirrors-golangci-lint
  rev: v1.54.2
  hooks:
  - id: golangci-lint
    args: ["run", "--timeout=5m"]
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.16.3
  hooks:
  - id: gitleaks
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  - id: shellcheck
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
