name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    # enable keyless signing via Sigstore OIDC
    env:
      COSIGN_EXPERIMENTAL: "1"
    permissions:
      contents: write  # allow creating GitHub releases via API
      packages: write
      id-token: write  # required for keyless Cosign OIDC
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Verify build
        run: |
          go build ./...
          go test ./...

      - name: Build binaries
        run: |
          mkdir dist
          for GOOS in linux darwin windows; do
            for GOARCH in amd64; do
              BIN="pilreg-$GOOS-$GOARCH"
              EXT=""
              if [ "$GOOS" = "windows" ]; then EXT=".exe"; fi
              GOOS=$GOOS GOARCH=$GOARCH CGO_ENABLED=0 go build -o "$BIN$EXT" ./cmd/pilreg
              tar -czvf "dist/$BIN.tar.gz" "$BIN$EXT"
              rm "$BIN$EXT"
            done
          done

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      # Clear any stale TUF metadata before keyless signing
      - name: Clear Sigstore TUF cache
        run: rm -rf ~/.sigstore

      # Keyless Cosign: init OIDC, verify identity, then sign blobs
      - name: Sign release archives (keyless)
        run: |
          cosign initialize
          for f in dist/*.tar.gz; do
            COSIGN_YES=true cosign sign-blob --output-signature "$f.sig" "$f"
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: dist/*
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Set up QEMU for multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Create and use a new buildx builder instance
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/go-pillage-registries:latest
            ghcr.io/${{ github.repository_owner }}/go-pillage-registries:${{ github.ref_name }}

      - name: Sign Docker images with Cosign (keyless)
        run: |
          cosign initialize
          COSIGN_YES=true cosign sign ghcr.io/${{ github.repository_owner }}/go-pillage-registries:latest
          COSIGN_YES=true cosign sign ghcr.io/${{ github.repository_owner }}/go-pillage-registries:${{ github.ref_name }}
