name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Verify build
        run: |
          go build ./...
          go test ./...

      - name: Build binaries
        run: |
          mkdir dist
          for GOOS in linux darwin windows; do
            for GOARCH in amd64; do
              BIN="pilreg-$GOOS-$GOARCH"
              EXT=""
              if [ "$GOOS" = "windows" ]; then EXT=".exe"; fi
              GOOS=$GOOS GOARCH=$GOARCH CGO_ENABLED=0 go build -o "$BIN$EXT" ./cmd/pilreg
              tar -czvf "dist/$BIN.tar.gz" "$BIN$EXT"
              rm "$BIN$EXT"
            done
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/go-pillage-registries:latest
            ghcr.io/${{ github.repository_owner }}/go-pillage-registries:${{ github.ref_name }}
